name: Build Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build docker-compose
      run: docker-compose build

    # Lancer les conteneurs avec docker-compose
    - name: Start containers
      run: docker-compose up -d

    # Exécuter la migration Laravel à l'intérieur du conteneur
    - name: Laravel migration
      run: docker-compose exec -it php-apache php artisan migrate

    # (Optionnel) Arrêter les conteneurs si nécessaire
    - name: Stop containers
      run: docker-compose down
