name: Build and Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build docker-compose
      run: docker-compose build

  start:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start docker-compose
      run: docker-compose up -d

  migrate:
    needs: start
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Artisan Migrate
      run: docker-compose exec -T php-apache php artisan migrate
  
  create: 
    needs: migrate
    runs-on: ubuntu-latest

    steps:
    - name: Run Artisan Create Objects
      run: docker-compose exec -T php-apache php artisan create:objects
